version: "2"

services:
  restful:
    build: restful/
    container_name: restful
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080

#  webapp:
#    build: webapp/
#    container_name: webapp
#    restart: always
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 4200:4200